#include "array.h"


INITIALIZE_ARRAY_S(int8_t);
INITIALIZE_ARRAY_S(int16_t);
INITIALIZE_ARRAY_S(int32_t);
INITIALIZE_ARRAY_S(int64_t);
INITIALIZE_ARRAY_S(uint8_t);
INITIALIZE_ARRAY_S(uint16_t);
INITIALIZE_ARRAY_S(uint32_t);
INITIALIZE_ARRAY_S(uint64_t);
INITIALIZE_ARRAY_S(float);
INITIALIZE_ARRAY_S(double);
INITIALIZE_ARRAY_S(string_t);